# Generated by Django 5.2.9 on 2025-12-19 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0015_rename_ordered_at_order_order_date_remove_order_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_date',
            new_name='ordered_at',
        ),
    ]
