# Generated by Django 5.2.9 on 2025-12-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0016_rename_order_date_order_ordered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='Name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booktable',
            name='Phone_number',
            field=models.BigIntegerField(),
        ),
    ]
