# Generated by Django 5.2.9 on 2025-12-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0017_alter_booktable_name_alter_booktable_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='delivery_address',
        ),
        migrations.AlterField(
            model_name='order',
            name='item_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
