# Generated by Django 5.2.9 on 2025-12-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0018_rename_address_order_delivery_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
