# Generated by Django 5.2.9 on 2025-12-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0019_alter_order_delivery_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(default='Cake'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='item_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
