# Generated by Django 5.2.9 on 2025-12-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0020_alter_order_delivery_address_alter_order_item_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='Phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
